

const  actionTypes = {
 REGISTER_SUCCESS:"REGISTER_SUCCE,SS",
 REGISTER_FAIL:"REGISTER_FAIL",
 LOGIN_SUCCESS:"LOGIN_SUCCESS",
 LOGIN_FAIL:"LOGIN_FAIL",
 LOGOUT:"LOGOUT",
    
 SET_MESSAGE:"SET_MESSAGE",
 CLEAR_MESSAGE:"CLEAR_MESSAGE",

 SET_COURSES:'SET_COURSES',
 SET_COURSES_FAIL:"SET_COURSES_FAIL",

 SET_SCHOOLS:'SET_SCHOOLS',
 SET_SCHOOLS_FAIL:"SET_SCHOOLS_FAIL"


}




export default actionTypes